python  -m torch.distributed.launch --nproc_per_node=1 swav/main_swav.py \
--data_path /mnt/sdc/code/ml_datasets/imagenet/data/train.X1/ \
--epochs 100 \
--base_lr 0.6 \
--final_lr 0.0006 \
--warmup_epochs 0 \
--batch_size 5 \
--size_crops 224 96 \
--nmb_crops 2 6 \
--min_scale_crops 0.14 0.05 \
--max_scale_crops 1. 0.14 \
--use_fp16 false \
--freeze_prototypes_niters 5005 \
--queue_length 3840 \
--epoch_queue_starts 15 --use_unlabeled_dataset=true --dump_path=/tmp/exp_out
